### ISSUE TITLE
About the focus_point_fn

### ISSUE THREAD

**Issue by thucz** [kylesargent/zeronvs#18]
Hi! Sorry to bother you. Could you provide the reference or the tutorial about how you compute the focus point? I still cannot understand the code here:

```
def focus_point_fn(poses: np.ndarray) -> np.ndarray:
    directions, origins = poses[:, :3, 2:3], poses[:, :3, 3:4]
    m = np.eye(3) - directions * np.transpose(directions, [0, 2, 1])
    mt_m = np.transpose(m, [0, 2, 1]) @ m
    focus_pt = np.linalg.inv(mt_m.mean(0)) @ (mt_m @ origins).mean(0)[:, 0]
    return focus_pt
```

**Comment by kylesargent** [comment]
This is the source: https://github.com/google-research/multinerf/blob/5b4d4f64608ec8077222c52fdf814d40acc10bc1/internal/camera_utils.py#L144

**Comment by thucz** [comment]
Thanks a lot!
