### ISSUE TITLE
Cannot reproduce some results

### ISSUE THREAD

**Issue by jiawei151** [kylesargent/ZeroNVS#5]
Thanks for your great work! I encountered a problem when I was trying to reproduce the result of [motorcycle.png](https://github.com/kylesargent/ZeroNVS/blob/main/motorcycle.png). I used all the default hyper-parameters but I got the following outputs:
![8a2b543f6b3af2d93ba9008a9312117](https://github.com/kylesargent/ZeroNVS/assets/126481534/537b94d8-a44c-4c9a-988b-45f6d892e1d6)
Unfortunately, I'm a freshman in diffusion model. Could you give me some suggestions? Thanks a lot!

**Comment by kylesargent** [comment]
Hi Jiawei, sorry to inconvenience you. This is (most likely) due to a bug identified in https://github.com/kylesargent/ZeroNVS/issues/4#issuecomment-1806558109. 

I just pushed the fix a moment ago. Can you please pull the new repo and new submodule and try again? Thanks.

**Comment by jiawei151** [comment]
> Hi Jiawei, sorry to inconvenience you. This is (most likely) due to a bug identified in [#4 (comment)](https://github.com/kylesargent/ZeroNVS/issues/4#issuecomment-1806558109).
> 
> I just pushed the fix a moment ago. Can you please pull the new repo and new submodule and try again? Thanks.

That fixed it! Thanks for your help!
