### ISSUE TITLE
That's  a great work! But I cannot reproduce the results in my device.

### ISSUE THREAD

**Issue by Kenkenzaii** [kylesargent/zeronvs#6]
Thanks for your open source and that's a really great work! 

I evaluate zeonvs.ckpt using the parameters that you provide on my desktop. Many of them show unsatisfied results as below. I would like to know whether something I get wrong when running. All the settings are the same as yours. Both linux and windows cannot show satisfied results. 

Are this method unstable or something haven't released yet?
 
Thanks for your assistance in advance.  
![Uploading fig_nvs.png…]()

**Comment by Kenkenzaii** [comment]
<img width="1792" alt="fig_nvs" src="https://github.com/kylesargent/ZeroNVS/assets/150908748/0d32710d-7e13-4f6c-b519-7285dbedf0c4">

**Comment by kylesargent** [comment]
Hi Kenkenzaii, can you verify it's not due to https://github.com/kylesargent/ZeroNVS/issues/5?

**Comment by Kenkenzaii** [comment]
Thanks for your help! I will try to fix it. Have a nice day!
