### ISSUE TITLE
Cannot reproduce test result

### ISSUE THREAD

**Issue by ezone123** [kylesargent/zeronvs#7]
code updated to the latest. When tested on the image "motorcycle.png", no vision was shown. no errors or warnings were present except resource limitation. 

https://github.com/kylesargent/ZeroNVS/assets/152853346/64eb4ba3-2941-4fc3-a631-f88451b6f621

**Comment by kylesargent** [comment]
I just re-ran the code and it seems to be working fine for me.

It seems you are rendering the model at iteration zero? If the training crashed due to resource limitations and rendered a video at step zero, obviously a NeRF which has not been trained at all would not reproduce the test results.

**Comment by ezone123** [comment]
I ran the prediction with launch_inference.sh in test mode and  the model was  released by your pre-trained model here. Still can't get the test result
![Uploading model.jpg…]()

**Comment by maoqingsunny** [comment]
I have encountered the same problem. Have you solved it?

**Comment by kylesargent** [comment]
@maoqingsunny  Unfortunately I cannot assist you without significantly more details regarding the failure to reproduce the result. 

Regarding my response earlier:
```It seems you are rendering the model at iteration zero? If the training crashed due to resource limitations and rendered a video at step zero, obviously a NeRF which has not been trained at all would not reproduce the test results.```

Does this apply to you?
