### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by aiyzs** [kylesargent/zeronvs#8]
I want to run the model on my 3090 device, but there is not enough memory. How can I adjust the relevant parameters to make it work

**Comment by Miaosheng1** [comment]
Same problem

**Comment by kylesargent** [comment]
Couple things you can try that seem to have no/ little performance impact:
(1) Batch size 6 -> 4 for the first training stage
(2) n_neurons for the proposal network 32 -> 16
(3) (Last resort) reduce number samples for either the proposal or nerf network Let me know if some combination of these steps can resolve the issues.
