### ISSUE TITLE
Generate novel views with 6dof+1 parameterization

### ISSUE THREAD

**Issue by Red-Fairy** [kylesargent/zeronvs#9]
Hi Kyle,

Thanks for your fantastic work! I'd like to know how to generate novel views with your model trained with $\mathbf{M}_{\mathrm{6DoF+1,~viewer}}$ parameterization. I tried to use the code in the "zeronvs_diffusion" submodule but found it only uses 3dof parameterization. Could you please provide any instructions?

Thanks in advance,
Rundong

**Comment by kylesargent** [comment]
The parameterization used depends on the setting of the conditioning mode, which you can see here: https://github.com/kylesargent/ZeroNVS/blob/5bfa13550594d20b17f4cd2ed434eebc144edea2/zeronvs_config.yaml#L148

If set to `7dof_quantile_scale`, the branch will be taken here when the conditioning is computed: 
https://github.com/kylesargent/zeronvs_diffusion/blob/4ffc80b94d279a735258a88686f43d83e7d04726/zero123/ldm/data/common.py#L329
